### PR TITLE
docs: readme

### PR DESCRIPTION
**Pull request by lirantal**
adding the missing description property field to the documentation in README.md

### CODE REVIEW

**Comment by 75lb** [comment]
hi.. thanks brother! 

`description` is not a property from this project, it's from command-line-usage and documented [here](https://github.com/75lb/command-line-usage#getusagedefinitions-options--string-)

I agree it should be more clear.. i will take your contribution and re-word it slightly..

**Comment by lirantal** [comment]
No problems. I've been command-line-args for one of my latest project and missed this option, only to find it later on when I reviewed the other examples and tests on this repo.
I do believe it's worth adding to the README to make it clear.

**Comment by 75lb** [comment]
ok.. done, i added links to the `.getUsage` docs [here](https://github.com/75lb/command-line-args#optiondefinition-)... hopefully that will help.

**Comment by lirantal** [comment]
Looks good, thanks!

**Pull request merged**
