### PR TITLE
Fix for isBoolean to increase compatibility

### PR DESCRIPTION
**Pull request by N4m**

### CODE REVIEW

**Comment by N4m** [comment]
As per your request, here is the pull request from #20

**Comment by N4m** [comment]
Hmm... must have missed something, or was that error there before?

**Comment by N4m** [comment]
yea, looking at the build history, looks like the build error occurred previously. I did the PR to master.

**Comment by 75lb** [comment]
I restarted the job which failed (the node 5 tests) and it passed.. it's a [bug in tape](https://github.com/substack/tape/issues/223), the test runner.. i'll switch to a different test runner soon.

**Comment by 75lb** [comment]
released in v3.0.1, thanks!

**Pull request merged**
