### PR TITLE
test a default option with a value equal to its default value

### PR DESCRIPTION
**Pull request by mykmelez**
This branch adds a test that demonstrates an issue that cropped up after #47. When I have a default option with a default value and `partial: true`, if I explicitly pass the default value to the option, then it ignores it and selects the first unknown value as the value for the option.

I.e. given 

```js
  const definitions = [
    { name: 'file', type: String, defaultOption: true, defaultValue: 'file1' },
  ]
  const argv = [ 'file1', '--two=3', '--four', '5' ]
  const options = commandLineArgs(definitions, { argv, partial: true })
```

I would expect `options` to be:

```js
{
  file: 'file1',
  _unknown: [ '--two', '3', '--four', '5' ]
}
```

But I actually get:

```js
{
  file: '3',
  _unknown: [ '--two', '--four', '5' ]
}
```

Per the test output:

>partial: defaultOption with value equal to defaultValue: AssertionError: { file: '3', _unknown: [ '--two', '--four', '5' ] } deepStrictEqual { file: 'file1', _unknown: [ '--two', '3', '--four', '5' ] }
>at Object.<anonymous> (/Users/myk/Projects/command-line-args/test/partial.js:54:5)
>at TestRunner.runTest (/Users/myk/Projects/command-line-args/node_modules/test-runner/src/lib/test-runner.js:171:29)
>at from.map.testItem (/Users/myk/Projects/command-line-args/node_modules/test-runner/src/lib/test-runner.js:91:21)
>at Array.map (native)
>at TestRunner.start (/Users/myk/Projects/command-line-args/node_modules/test-runner/src/lib/test-runner.js:89:44)
>at process.TestRunner.process.on (/Users/myk/Projects/command-line-args/node_modules/test-runner/src/lib/test-runner.js:46:16)
>at emitOne (events.js:101:20)
>at process.emit (events.js:191:7)

I took a swing at output.js but couldn't find a solution to the problem that doesn't break other tests. So for now this branch just demonstrates the problem; it doesn't attempt to fix it.

### CODE REVIEW

**Comment by 75lb** [comment]
thanks for this, will take a look as soon as i get chance 👍

**Comment by mykmelez** [comment]
FWIW, the reason I ran into this is that I was working around #47 by setting the default value of a default option to `argv[0]`, since the documented semantics of my application are that argv[0] is always the value of that option:

```js
   const optionDefinitions = [
      …
      { name: 'path', alias: 'p', type: String, defaultOption: true,
        defaultValue: argv[0] || process.cwd() },
      …
   ];
```

Now that #47 is fixed, however, I don't need to work around it anymore, so I've removed the workaround in conjunction with upgrading to version 4.0.3 (in https://github.com/mozilla/qbrt/pull/60). Nevertheless, it's still possible to run into this bug, both in my application and in others.

In my experimentation, I managed to fix it by lazily setting an option to its default value in `Output::get()`, rather than doing so eagerly in the `Output` constructor (via `Output::_assignDefaultValues())`. But that broke other tests, and it wasn't clear to me how to fix them.

**Comment by 75lb** [comment]
fixed and released in v4.0.4, thanks again.. let me know if you find anything else 👍

**Comment by mykmelez** [comment]
Thanks, @75lb, will do!

**Pull request merged**
