### PR TITLE
Support case insensitive command line options

### PR DESCRIPTION
**Pull request by peazncheez**
Adds a caseSensitive field to OptionDefinition to support parsing certain arguments in a case insensitive manner. The default behavior continues to treat all command line arguments as case sensitive.

The UNIX-based command line is traditionally case sensitive, but the Windows command line is not. I'm working on a Windows application and we're currently using this library, but we'd like our args to be parsed in a case-insensitive manner.

### CODE REVIEW

**Comment by peazncheez** [comment]
@75lb , mind reviewing / allowing the CI to run? And let me know if I shouldn't check in those `dist` files because they're generated at a later stage or something.

**Comment by 75lb** [comment]
morning, thanks for the new feature - sounds good to me.. I will review it later today.. Yes, the `dist` should be checked in but don't worry about that - I'll take it from here as I might add some futher updates to freshen the library up..

**Comment by peazncheez** [comment]
hey @75lb , any updates? 🙂

**Comment by 75lb** [comment]
Will you need the granularity of being able to set `caseSensitive` at the option level or can we set the flag once when invoking the [parse function?](https://github.com/75lb/command-line-args/blob/master/doc/API.md#commandlineargsoptiondefinitions-options--object-)? E.g. 

```js
commandLineArgs(optionDefinitions, { caseInsensitive: true })
```

Also, the general convention is to enable an option flag by setting it to `true`, not `false`, so I will probably change the option name to `caseInsensitive`..

**Comment by 75lb** [comment]
Why are aliases always case-sensitive? Wouldn't it be more consistent to enable or disable case-sensitivity across the board?

**Comment by peazncheez** [comment]
Hey @75lb , thanks for the feedback. I had originally implemented the per-option case sensitivity granularity since that would be most flexible, but it's not necessary for my use case and I agree the additional complexity likely isn't worth it.

Pushed up some commits which:

- switch over to a single parse-level case insensitivity flag rather than the previous per-option-definition flags
- makes the case sensitivity flag apply to aliases
- renames the flag to be `caseInsensitive` as you recommended

**Comment by 75lb** [comment]
Merged and released in [v5.2.0](https://github.com/75lb/command-line-args/releases/tag/v5.2.0), thanks. 👍

**Comment by peazncheez** [comment]
Awesome, thank you!

**Pull request merged**
